# 上游
upstream_project_url: https://github.com/upstream-owner/upstream-repo
upstream_tag_template: "v{version}"

specfile_path: SPECS/hmcl.spec
files_to_sync:
  - SPECS/hmcl.spec

upstream_package_name: HMCL
downstream_package_name: hmcl

actions:
  create-archive:
    - bash -c "rm -f *.jar HMCL-*.jar"
    - spectool -g SPECS/hmcl.spec
    - bash -c "ls -1 HMCL-*.jar 2>/dev/null | head -n 1"

jobs:
  - job: copr_build
    trigger: release
    owner: mapping1
    project: HMCL

  - job: copr_build
    trigger: pull_request
    owner: mapping1
    project: HMCL
