# 上游
upstream_project_url: https://github.com/upstream-owner/upstream-repo
upstream_tag_template: "v{version}"

specfile_path: SPECS/hmcl.spec
files_to_sync:
  - SPECS/hmcl.spec

upstream_package_name: upstream-package
downstream_package_name: your-package

jobs:
  - job: copr_build
    trigger: release
    owner: mapping1
    project: HMCL

